### ISSUE TITLE
Unable to escape parentheses in LDAP search filter

### ISSUE THREAD

**Issue by amccarty** [ContinuumIO/flask-ldap-login#17]
We have a customer who has Active Directory groups with parentheses in group names. For some reason, regular "\" escapes don't work, nor do unicode escapes, or any amount of quoting, bracketing, etc. that I've tried.  This affects both Wakari and Anaconda Server. Here's a test example (with working credentials):

```
{
    "accounts":"wk_server.plugins.accounts.ldap2",
    "LDAP" : {
        "URI": "ldap://dc1.testcio.com",
        "BIND_DN": "CN=Slim Pickens,OU=Austin,DC=testcio,DC=com",
        "BIND_AUTH": "C0nt1nuum!",
        "USER_SEARCH": {"base": "OU=Austin,DC=testcio,DC=com",
                        "filter": "(&(objectCategory=Person)(memberOf=CN=Testers (1),CN=Users,dc=testcio,dc=com)(sAMAccountName=%(username)s))"
        }
    }
}
```
**Output from flask-ldap-login-check:**
```
-bash-4.1$ /opt/wakari/wakari-server/bin/flask-ldap-login-check wk_server.wsgi:app -u slimp -p C0nt1nuum!
Loading config from /opt/wakari/wakari-server/etc/wakari/config.json
Loading config from /opt/wakari/wakari-server/etc/wakari/wk-server-config.json
11253 | 2015-12-14 14:43:22.405 INFO: Initialize Wakari LDAP [__init__.py:50]
11253 | 2015-12-14 14:43:22.410 INFO: Days left in license: 143 [wsgi.py:12]
11253 | 2015-12-14 14:43:22.410 INFO: Wakari Server Ready [wsgi.py:12]
11253 | 2015-12-14 14:43:22.411 DEBUG: Connecting to ldap server ldap://dc1.testcio.com [__init__.py:219]
11253 | 2015-12-14 14:43:22.412 DEBUG: Performing bind/search [__init__.py:154]
11253 | 2015-12-14 14:43:22.412 DEBUG: Binding with the BIND_DN CN=Slim Pickens,OU=Austin,DC=testcio,DC=com [__init__.py:162]
11253 | 2015-12-14 14:43:22.548 DEBUG: Search for base=OU=Austin,DC=testcio,DC=com filter=(&(objectCategory=Person)(memberOf=CN=Testers (1),CN=Users,dc=testcio,dc=com)(sAMAccountName=slimp)) [__init__.py:176]
Traceback (most recent call last):
  File "/opt/wakari/wakari-server/bin/flask-ldap-login-check", line 6, in <module>
    sys.exit(main())
  File "/opt/wakari/wakari-server/lib/python2.7/site-packages/flask_ldap_login/check.py", line 29, in main
    userdata = app.ldap_login_manager.ldap_login(args.username, args.password)
  File "/opt/wakari/wakari-server/lib/python2.7/site-packages/flask_ldap_login/__init__.py", line 246, in ldap_login
    result = self.bind_search(username, password)
  File "/opt/wakari/wakari-server/lib/python2.7/site-packages/flask_ldap_login/__init__.py", line 177, in bind_search
    results = self.conn.search_s(base, scope, filt, attrlist=self.attrlist)
  File "/opt/wakari/wakari-server/lib/python2.7/site-packages/ldap/ldapobject.py", line 552, in search_s
    return self.search_ext_s(base,scope,filterstr,attrlist,attrsonly,None,None,timeout=self.timeout)
  File "/opt/wakari/wakari-server/lib/python2.7/site-packages/ldap/ldapobject.py", line 545, in search_ext_s
    msgid = self.search_ext(base,scope,filterstr,attrlist,attrsonly,serverctrls,clientctrls,timeout,sizelimit)
  File "/opt/wakari/wakari-server/lib/python2.7/site-packages/ldap/ldapobject.py", line 541, in search_ext
    timeout,sizelimit,
  File "/opt/wakari/wakari-server/lib/python2.7/site-packages/ldap/ldapobject.py", line 99, in _ldap_call
    result = func(*args,**kwargs)
ldap.FILTER_ERROR: {'desc': 'Bad search filter'}
```
**NOTE**: The slimp user is also member of the "Testers" group, so to demonstrate a working example you can substitute "Tester" for "Tester (1)" in the config above.

**Successful output via python and ldapsearch:**

Python:
```
>>> import ldap
>>> 
>>> con = ldap.initialize("ldap://dc1.testcio.com")
>>> dn = "CN=Slim Pickens,OU=Austin,DC=testcio,DC=com"
>>> pw = "C0nt1nuum!"
>>> base_dn = "OU=Austin,DC=testcio,DC=com"
>>> filter = "(&(objectCategory=Person)(memberOf=CN=Testers \(1\),CN=Users,dc=testcio,dc=com))"
>>> attrs = ['sAMAccountName']
>>> con.simple_bind_s( dn, pw )
(97, [], 1, [])
>>> con.search_s( base_dn, ldap.SCOPE_SUBTREE, filter, attrs )
[('CN=Slim Pickens,OU=Austin,DC=testcio,DC=com', {'sAMAccountName': ['slimp']})]
```

Ldapsearch:
```
ldapsearch -x  -b "DC=testcio,DC=com" -H ldap://dc1.testcio.com -D "CN=Slim Pickens,OU=Austin,DC=testcio,DC=com"  -W "(&(objectCategory=Person)(memberO
f=CN=Testers \(1\),CN=Users,dc=testcio,dc=com))" | grep -i samaccountname 
Enter LDAP Password: 
sAMAccountName: slimp
```

**Comment by amccarty** [comment]
OK, think we solved this by using a double escape (thanks @bkreider ): 
`"filter": "(&(objectCategory=Person)(memberOf=CN=Testers \\(1\\),CN=Users,dc=testcio,dc=com)(sAMAccountName=%(username)s))"`
