### ISSUE TITLE
Cannot install using pip on Python 3 

### ISSUE THREAD

**Issue by felipemafra** [ContinuumIO/flask-ldap-login#36]
Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\IamAnUser\AppData\Local\Temp\pycharm-packaging\python-ldap\setup.py", line 53
        print name + ': ' + cfg.get('_ldap', name)
                 ^
    SyntaxError: invalid syntax

**Comment by categulario** [comment]
you can install python-ldap manually using `pip install --pre python-ldap`
